apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: luck-infrastructure
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: broker-id-setter
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          BROKER_ID=$(echo $HOSTNAME | sed -n 's/.*-\(.*\)$/\1/p')
          echo "broker.id=$BROKER_ID" >> /etc/kafka/server.properties
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.0.0
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cs:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://$(KAFKA_BROKER_ID).kafka-headless.default.svc.cluster.local:9092
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "luck-infrastructure-kafka"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "true"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: kafka-volume
          mountPath: /var/lib/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: luck-kafka-nfs-csi
        resources:
          requests:
            storage: 10Gi
  updateStrategy:
    type: RollingUpdate
  
---
apiVersion: v1
kind: Service
metadata:
  namespace: luck-infrastructure
  name: kafka-headless
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 3011
      name: kafka