apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-sc-pvc
  namespace: luck-infrastructure
spec:
  storageClassName: luck-jenkins-nfs-csi
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce