apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: luck-jenkins-nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.31.70
  share: /data/nfs/jenkins-sc-pvc
reclaimPolicy: Delete
volumeBindingMode: Immediate